name: CI/CD Pipeline

# When should this workflow run?
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Define the jobs that will run
jobs:
  # Job 1: Test Backend
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get the code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    # Step 3: Install dependencies
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
    
    # Step 4: Run tests
    - name: Run backend tests
      working-directory: ./backend
      run: npm test

  # Job 2: Test Frontend
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
    
    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test

  # Job 3: Test CLI
  cli-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: cli/package-lock.json
    
    - name: Install CLI dependencies
      working-directory: ./cli
      run: npm ci
    
    - name: Test CLI commands
      working-directory: ./cli
      run: |
        npm test
        node bin/backup-guardian --help
        node bin/backup-guardian version
